### ISSUE TITLE
Big Scatter Plots

### ISSUE THREAD

**Issue by saulshanabrook** [uwdata/falcon#91]
Have you thought about how this could support scatter plots that are backed by lots of data? To give a motivating example, check out the last two plots in this file: https://github.com/Quansight/mapd/blob/673a11518294bd59bd0986e64ca7f8669fdf147d/notebooks/Ibis%20%2B%20Altair.ipynb

The first is rendered client side and uses 10k rows and the second is rendered on the backend with MapD and uses all 570k rows.

My intuition is that since the image is a rather small size, the data to make up that visualization can't be that large. The worst case would be sending back an opacity for each pixel. Which seems a lot like a very fine heatmap. So I am curious if you have tried examples like this and if you think there is anything fundamental preventing this from being rendered client side instead of server side.

**Comment by saulshanabrook** [comment]
Maybe you already did this in https://github.com/uwdata/falcon/issues/76? Do you have an example of that?

**Comment by domoritz** [comment]
Oh wow, that notebook looks awesome. I’m actually working on some transform compilation for Vega-Lite so we should get on a Skype call and talk about what we’re up to!

Falcon currently supports heatmaps 1D and 2D histograms. It’ll look very similar to your map but it won’t render individual marks. I don’t plan to add support for rendering individual marks because an aggregated plot will always be more useful when the data gets large.
