### ISSUE TITLE
Enable minification in parcel builds

### ISSUE THREAD

**Issue by domoritz** [uwdata/falcon#94]
It breaks the flight demo right now: https://github.com/uwdata/falcon/issues/92.

**Comment by tarekrached** [comment]
Not sure if this is related, but I'm also unable to minify due to a [strangely-built](https://github.com/google/flatbuffers/blob/master/package.json#L14) flatbuffers package, which is upstream of @apache-arrow/es2015-esm.  I don't have a path forward on this, still trying to isolate the minification issue locally.

You may want to investigate depending on the omni `apache-arrow` instead?

**Comment by domoritz** [comment]
I was able to use the arrow version with minification but the mapd version broke. 

https://github.com/parcel-bundler/parcel/issues/1887 might fix it but not sure.

**Comment by tarekrached** [comment]
Interesting - my issue was with the arrow version, and only manifests in the `create-react-app` production build, which has aggressive minification settings.  Sounds like it's a different issue.

**Comment by tarekrached** [comment]
👍 no worries - i've been [bugging those folks](https://github.com/apache/arrow/issues/2640), too. 

(I've been diving deep into `node_modules`, if you can't tell 😃)

**Comment by domoritz** [comment]
Oh the unknown depts of node_modules.
